server:
  port: 9098

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysqluser
    password: mysqluser
    url: r2dbc:mysql://172.31.3.51:3306/DW_PERMISSION_TEST?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  sqltoy:
    sql-resources-dir: classpath:sqltoy
    debug: true
#    unify-fields-handler:
