server:
  port: 8989
  servlet:
    context-path: /
    session:
      tracking-modes: cookie
      cookie:
        http-only: true

spring:
  aop:
    auto: true
    proxy-target-class: true
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 30
      max-request-size: 30
      location: /upload
  mail:
    host:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 3
        max-active: 1000
        max-wait: 20
  freemarker:
    template-loader-path: classpath:/template/
    allow-request-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: rc
    suffix: .ftl
    settings:
      number_format: 0.##

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://127.0.0.1:3306/c_study?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password:
    druid:
      initial-size: 10
      min-idle: 5
      max-wait: 1000
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall,log4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.liangqinghai.study.mbp.module
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      capitalMode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

custom:
  free-maker:
    author: Mr.Liang
    keyword: study
    description: desc