server:
  port: 9988
  servlet:
    context-path: /

logging:
  config: classpath:log4j.xml
spring:
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 30000
        idle-timeout: 30000
        validation-timeout: 3000
        max-pool-size: 20
        min-idle: 10
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
      primary: master
      strict: false
      datasource:
        master:
          username: root
          password:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3306/c_test?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          hikari:
            is-read-only: false
  aop:
    auto: true
    proxy-target-class: true

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

  messages:
    basename: static/i18n/messages

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  devtools:
    restart:
      enabled: true

mybatis-plus:
  configuration:
    cache-enabled: true
    default-executor-type: reuse
    jdbc-type-for-null: null
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: auto
      table-prefix: t_
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
    super-mapper-class: com.baomidou.mybatisplus.core.mapper.BaseMapper
  type-enums-package: cn.liangqinghai.study.mbp.enums
  type-aliases-package: cn.liangqinghai.study.mbp.*.*.models
  type-handlers-package: cn.liangqinghai.study.mbp.typehandler

mbp:
  email:
    enable: false
    send: hello@live.com
  generator:
    author: Mr.Liang
    package-path: cn.liangqinghai.study.mbp.gen
  demo:
    enable: false
  address:
    enable: true
  password:
    maxRetryCount: 5
  path:
    file-path: /data/filepath
    resource-handler: /data/profile/**
    resource-path: /data/profile/
    prefix:
      avatar: avatar/
      download: download/
      upload: upload/
  xss:
    enable: true
    exclude-fields:
      - noticeContent
    exclude-urls:
      - /system/notice/*

shiro:
  index-url: /index
  login-url: /login
  unauth-url: /unauth
  session:
    db-sync-period: 1
    expire-time: 30
    validation-interval: 10
    max-session: 1
    kickout-after: false
  remember-me-cookie:
    domain:
    path: /
    http-only: true
    max-age: 1