server:
  port: 9988
  servlet:
    context-path: /

logging:
  config: classpath:log4j.xml
spring:
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 30000
        idle-timeout: 30000
        validation-timeout: 3000
        max-pool-size: 20
        min-idle: 10
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
      primary: master
      strict: false
      datasource:
        master:
          username: root
          password:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3306/c_test?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          hikari:
            is-read-only: false
  aop:
    auto: true
    proxy-target-class: true

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

  messages:
    basename: static/i18n/messages

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  devtools:
    restart:
      enabled: true

