server:
  port: 8990

spring:
  application:
    name: dubbo-client

dubbo:
  application:
    name: dubbo-client
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.liangqinghai.study.spring.dubbo
  provider:
    timeout: 20000