server:
  port: 9798

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    name: helloWorld
    username: mysqluser
    password: mysqluser
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
    url: r2dbc:mysql://172.31.3.51:3306/DW_PERMISSION_TEST?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  #    url: r2dbc:h2:mem://in-memory/helloWorld?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      springframework:
        data: debug
        r2dbc: trace