server:
  port: 8888
spring:
  application:
    name: kotlin-spring-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lqh?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: lqh
    password: lqh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true